# Generated by Django 3.2 on 2022-08-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
