# Generated by Django 3.2 on 2022-08-20 09:22

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_timestamp_recipe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipes.validators.valid_unit_of_measure]),
        ),
    ]
