# Generated by Django 3.2 on 2022-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_quantity_as_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
