# Generated by Django 3.2 on 2022-08-10 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField()),
                ('publish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, unique=True, verbose_name='إسم الموظف')),
                ('password', models.CharField(max_length=30, verbose_name='كلمة المرور')),
                ('phone', models.CharField(max_length=12)),
                ('birth_day', models.DateField(default=django.utils.timezone.now, verbose_name='تأريخ الميلاد')),
                ('email', models.EmailField(max_length=254, verbose_name='الأيميل')),
                ('status', models.BooleanField(verbose_name='الحاله')),
            ],
        ),
        migrations.CreateModel(
            name='PhonesNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.IntegerField(verbose_name=' رقم المخزن')),
                ('stock_name', models.CharField(max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cutting_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, unique=True)),
                ('lname', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cutting_app.phonesnumber')),
            ],
        ),
    ]
