# Generated by Django 3.2 on 2022-08-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
