# Generated by Django 3.2 on 2022-08-10 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutting_app', '0002_alter_articles_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 10, 21, 50, 52, 294846, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
