# Generated by Django 3.2 on 2022-08-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting_app', '0004_auto_20220810_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='publish',
        ),
    ]
